spring:
  application:
    name: stocker
    
server:
  port: 40401
  servlet:
    context-path: /stocker

app-config:
  sourceUrl: https://www.alphavantage.co/query
  function: function=TIME_SERIES_DAILY_ADJUSTED
  symbol: symbol=
  apiKey: apikey=6BTX1GJFPPY37E4K
  